# H2
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2
# Datasource
#spring.datasource.url=jdbc:h2:file:~/test
#spring.datasource.username=sa
#spring.datasource.password=
#spring.datasource.driver-class-name=org.h2.Driver


#NewFeed URL http://newsapi.org/v2/everything?q=plano%20texas&apiKey=07a54746c3774c6c828c7dfd9c0e5699
newsFeedEndpointURL: http://newsapi.org/v2/everything
defaultSearchKey: plano texas
newsFeedapiKey: 07a54746c3774c6c828c7dfd9c0e5699

server:
  port: 8080
  session:
    cookie:
      name: UISESSION
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
  thymeleaf:
    cache: false
  security:
    user:
      name: admin
      password: admin
    oauth2:
      client:
        registration:
          github:
            client-id: a82def5db4cf77d24eb9
            client-secret: 429ccd1c8fbe59e139c9b38bf91899e45123dbab
            access-token-uri: https://github.com/login/oauth/access_token
            scope: read:user,user:email
            provider: github
            redirect-uri: http://localhost:8080/primeContent/Home/plano
            client-authentication-method: basic
            authorization-grant-type: authorization_code